services:
  music-analyzer:
    image: ghcr.io/nichuanfang/audio-analyzer:latest
    container_name: music-analyzer
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MUSIC_ROOT=/music      # 音乐根目录
      - PORT=8000              # 端口
      - MAX_ANALYSIS_SECONDS=300 # 最大分析时长(秒)
    volumes:
      - /mnt/nas/music:/music:ro